Css canvas medical - Nimrod Castano
nimcastano/c0323-code-solutions pull request #59
Opened 2023-04-05 18:43 UTC by nimcastano

<img width="1294" alt="Screenshot 2023-04-05 at 11 43 32 AM" src="https://user-images.githubusercontent.com/126118228/230175264-37dab3ca-b44d-4717-b725-3ea16558828b.png">

2023-04-05 18:49 UTC, shawnkost requested changes
Please include screenshots of the other sections, or a gif of you scrolling the whole page, so I can verify the whole page looks like the example image

2023-04-05 18:57 UTC, nimcastano commented
![css-canvas-medical gif](https://user-images.githubusercontent.com/126118228/230178462-8a7c8ba2-1758-4570-b13e-5b5e3ce2c958.gif)

2023-04-05 22:53 UTC, shawnkost requested changes
Very nicely done Nimrod! Just a couple changes requested here

2023-04-05 22:53 UTC, shawnkost commented on css-canvas-medical/index.html
> +        <img id="logo" src="images/logo-blue.svg">
Don't forget the `alt` attribute

2023-04-05 22:53 UTC, shawnkost commented on css-canvas-medical/index.html
> +          <img src="images/logo-white.png" class="white-logo">
Don't forget the `alt` attribute

2023-04-13 20:40 UTC, shawnkost approved these changes
👍🏻

2023-04-13 21:19 UTC, closed without merging